//
// CHRISTOULAS MATHAFAQUERS
//

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	tests_ckatsak_v1alpha1 "github.com/ckatsak/crdgentest/pkg/apis/tests.ckatsak/v1alpha1"
	versioned "github.com/ckatsak/crdgentest/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ckatsak/crdgentest/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ckatsak/crdgentest/pkg/client/listers/tests.ckatsak/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DisttateInformer provides access to a shared informer and lister for
// Disttates.
type DisttateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DisttateLister
}

type disttateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDisttateInformer constructs a new informer for Disttate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDisttateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDisttateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDisttateInformer constructs a new informer for Disttate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDisttateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestsV1alpha1().Disttates(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestsV1alpha1().Disttates(namespace).Watch(options)
			},
		},
		&tests_ckatsak_v1alpha1.Disttate{},
		resyncPeriod,
		indexers,
	)
}

func (f *disttateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDisttateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *disttateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tests_ckatsak_v1alpha1.Disttate{}, f.defaultInformer)
}

func (f *disttateInformer) Lister() v1alpha1.DisttateLister {
	return v1alpha1.NewDisttateLister(f.Informer().GetIndexer())
}
