//
// CHRISTOULAS MATHAFAQUERS
//

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/ckatsak/crdgentest/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Disttates returns a DisttateInformer.
	Disttates() DisttateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Disttates returns a DisttateInformer.
func (v *version) Disttates() DisttateInformer {
	return &disttateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
