//
// CHRISTOULAS MATHAFAQUERS
//

// This file was automatically generated by lister-gen

package v1alpha1

// DisttateListerExpansion allows custom methods to be added to
// DisttateLister.
type DisttateListerExpansion interface{}

// DisttateNamespaceListerExpansion allows custom methods to be added to
// DisttateNamespaceLister.
type DisttateNamespaceListerExpansion interface{}
